language: python
dist: focal
os: linux

python:
  - "3.8"
  - "3.9"
  - "3.10"

# Настройка виртуального дисплея для GUI
before_install
  - sudo apt-get update
  - sudo apt-get install -y xvfb
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

# Установка зависимостей
install:
  - pip install --upgrade pip wheel setuptools
  - pip install cython
  - pip install kivy[base]

# Проверка запуска приложения
script:
  - python main.py
